name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.7.0"

jobs:
  check-hashes:
    name: check-hashes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry ${{ env.POETRY_VERSION }}
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Compare Hashes
        run: |
          ./Makefile
